### PR TITLE
Test gpuCI on dask-image

### PR DESCRIPTION
**Pull request by charlesbluca**

### CODE REVIEW

**Comment by charlesbluca** [comment]
rerun tests

**Comment by charlesbluca** [comment]
rerun tests

**Comment by charlesbluca** [comment]
rerun tests

**Comment by jakirkham** [comment]
Would it make sense to go ahead and set this up on dask-image and test there?

**Comment by charlesbluca** [comment]
I would prefer setting it up on dask-image after merging in https://github.com/dask/dask-image/pull/248, as if we enable it first it will add a failing check to all PRs until the relevant build files are in, which caused some noisiness for Dask / Distributed.

This is somewhat smaller of a project though so I'm okay with enabling first if you think that would make things easier

**Comment by jakirkham** [comment]
Ah ok. Sure this seems fine 🙂

Was just thinking it might simplify things to set it up on dask-image directly, but happy to defer to you

**Pull request closed without merging**
